package org.fangsoft.testcenter.web.view;

import java.io.PrintWriter;public class StartTestView extends HtmlView{
   private static final long serialVersionUID = 1L;
   public void output(PrintWriter writer){
      writer.println("<!DOCTYPE html>");
      writer.println("<html lang=\"en\">");
      writer.println("<head>");
      writer.println("    <meta charset=\"UTF-8\">");
      writer.println("    <title>FangSoft</title>");
      writer.println("</head>");
      writer.println("<body>");
      writer.println("");
      writer.println("<div align=\"center\" style=\"background-color: rgb(255,255,204); width: 100%; height: 10%;\">");
      writer.println("    <span style=\"font-size: medium; color: BLUE; \">");
      writer.println("        <h1>Fangsoft考试中心</h1>");
      writer.println("    </span>");
      writer.println("</div>");
      writer.println("");
      writer.println("<table width=\"100%\" border=\"0\">");
      writer.println("    <tr>");
      writer.println("        <td colspan=\"3\" valign=\"top\" bgcolor=\"#FFFFCC\">");
      writer.println("            <strong>开始考试</strong>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("    <tr>");
      writer.println("        <td width=\"49%\">");
      writer.println("            考试名称：");
      writer.println("        </td>");
      writer.println("        <td width=\"50%\">");
      writer.println("            JAVA");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=\"49%\">");
      writer.println("            考试时间：");
      writer.println("        </td>");
      writer.println("        <td width=\"50%\">");
      writer.println("            10分钟");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=\"49%\">");
      writer.println("            考试题数：");
      writer.println("        </td>");
      writer.println("        <td width=\"50%\">");
      writer.println("            3");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=\"49%\">");
      writer.println("            考试总分：");
      writer.println("        </td>");
      writer.println("        <td width=\"50%\">");
      writer.println("            3");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=\"49%\">");
      writer.println("            参考人：");
      writer.println("        </td>");
      writer.println("        <td width=\"50%\">");
      writer.println("            tong");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("</table>");
      writer.println("<table width=\"100%\" border=\"0\">");
      writer.println("    <tr>");
      writer.println("        <td colspan=\"3\" valign=\"top\" bgcolor=\"#FFFFCC\">");
      writer.println("            <strong>开始考试</strong>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("</table>");
      writer.println("");
      writer.println("</body>");
      writer.println("</html>");
      writer.println("");
      writer.println("<form action=\"this.getUrlCommitTestAction()\" method=\"get\" name=\"takeTestForm\" id=\"takeTestForm\">");
      writer.println("    <table width=\"100%\" border=\"0\">");
      writer.println("        <tr>");
      writer.println("            <td colspan=\"2\" bgcolor=\"#FFFFCC\">");
      writer.println("                <div align=\"left\">");
      writer.println("                    <strong>考试试题</strong>");
      writer.println("                </div>");
      writer.println("            </td>");
      writer.println("        </tr>");
      writer.println("");
      writer.println("        <tr>");
      writer.println("            <td width=\"6%\">");
      writer.println("                1.");
      writer.println("            </td>");
      writer.println("            <td width=\"94%\">");
      writer.println("                getName()");
      writer.println("            </td>");
      writer.println("        </tr>");
      writer.println("");
      writer.println("        <tr>");
      writer.println("            <td>");
      writer.println("            </td>");
      writer.println("            <td>");
      writer.println("                <ol>");
      writer.println("                    <li>");
      writer.println("                        <input type=\"checkbox\">");
      writer.println("                        xxx");
      writer.println("                    </li>");
      writer.println("                </ol>");
      writer.println("            </td>");
      writer.println("        </tr>");
      writer.println("");
      writer.println("        <tr>");
      writer.println("            <td>");
      writer.println("            </td>");
      writer.println("            <td>");
      writer.println("            </td>");
      writer.println("        </tr>");
      writer.println("        <tr>");
      writer.println("            <td colspan=\"2\">");
      writer.println("                <div align=\"center\">");
      writer.println("                    <a href=\"testResult.html\" class=\"button\">完成考试</a>");
      writer.println("                </div>");
      writer.println("            </td>");
      writer.println("        </tr>");
      writer.println("    </table>");
      writer.println("</form>");

   }
}