--drop table --
DROP TABLE "TEST" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "CHOICEITEM" CASCADE CONSTRAINTS;
--create table--
      CREATE TABLE "TEST"
  ("TT_ID" INTEGER NOT NULL,
   "TT_NAME" VARCHAR2(80) NOT NULL,
    "TT_NUMQUESTION" INTEGER NOT NULL,
    "TT_TIMELIMITMIN" INTEGER NOT NULL,
    "TT_DESCRIPTION" VARCHAR2(255) NULL,
    "TT_SCORE" INTEGER NULL);

ALTER TABLE "TEST" ADD CONSTRAINT "PK_TEST" PRIMARY KEY ("TT_ID");

CREATE TABLE "QUESTION"
("QN_ID" INTEGER NOT NULL,
 "QN_NAME" VARCHAR2(512) NOT NULL,
 "QN_ANSWER" VARCHAR2(512) NULL,
 "QN_SCORE" INTEGER NULL,
 "QN_TEST_ID" INTEGER NULL);

ALTER TABLE "QUESTION"  ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY ("QN_ID");

CREATE TABLE "CHOICEITEM"
("CM_ID" INTEGER NOT NULL,
 "CM_NAME" VARCHAR2(512) NOT NULL,
 "CM_CORRECT" INTEGER DEFAULT 0 NULL,
 "CM_QUESTION_ID" INTEGER NULL);

ALTER TABLE "CHOICEITEM" ADD CONSTRAINT "PK_CHOICEITEM" PRIMARY KEY ("CM_ID");


--drop sequence -
DROP SEQUENCE "SEQ_TEST" ;
DROP SEQUENCE "SEQ_QUESTION" ;
DROP SEQUENCE "SEQ_CHOICEITEM" ;
--create sequence--
CREATE SEQUENCE "SEQ_TEST" ;
CREATE SEQUENCE "SEQ_QUESTION";
CREATE SEQUENCE "SEQ_CHOICEITEM";

# private String userId ;
# private String password ;
# private String email;

CREATE TABLE "CUSTOMER"
("CR_ID" INTEGER NOT NULL,
 "CR_NAME" VARCHAR2(80) NOT NULL,
 "CR_password" VARCHAR2(255) NOT NULL,
 "CR_email" VARCHAR2(255) NOT NULL);


CREATE TABLE "TESTRESULT"
("TRT_ID" INTEGER NOT NULL,
 "TRT_NAME" VARCHAR2(80) NOT NULL,
 "TRT_NUMQUESTION" INTEGER NOT NULL,
 "TRT_TIMELIMITMIN" INTEGER NOT NULL,
 "TRT_DESCRIPTION" VARCHAR2(255) NULL,
 "TRT_SCORE" INTEGER NULL);

CREATE TABLE "QUESTIONRESULT"
("QRT_ID" INTEGER NOT NULL,
 "QRT_NAME" VARCHAR2(80) NOT NULL,
 "QRT_NUMQUESTION" INTEGER NOT NULL,
 "QRT_TIMELIMITMIN" INTEGER NOT NULL,
 "QRT_DESCRIPTION" VARCHAR2(255) NULL,
 "QRT_SCORE" INTEGER NULL);

