package org.fangsoft.testcenter.web.view;

import java.io.PrintWriter;public class TestcenterView extends HtmlView{
   private static final long serialVersionUID = 1L;
   public void output(PrintWriter writer){
      writer.println("<meta charset=\"UTF-8\">");
      writer.println("<title>");
      writer.println("    FangSoft");
      writer.println("</title>");
      writer.println("<div align=\"center\" style=\"background-color: rgb(255,255,204); width: 100%; height: 5%;\">");
      writer.println("  <span style=\"font-size: medium; color: BLUE; \">");
      writer.println("    <h1>");
      writer.println("      Fangsoft考试中心");
      writer.println("    </h1>");
      writer.println("  </span>");
      writer.println("</div>");
      writer.println("<p>");
      writer.println("    欢迎，tong");
      writer.println("    <a href=\"login.html\">");
      writer.println("        登出");
      writer.println("    </a>");
      writer.println("</p>");
      writer.println("");
      writer.println("<table width=\"99%\" border=\"0\">");
      writer.println("    <tr>");
      writer.println("        <td bgcolor=\"#FFFFCC\">");
      writer.println("            <strong>考试</strong>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("    <tr>");
      writer.println("        <td>");
      writer.println("            <div align=\"left\">");
      writer.println("                <ul>");
      writer.println("                    <li>");
      writer.println("                        <a href=\"testDetail.html\">java</a>");
      writer.println("                    </li>");
      writer.println("                </ul>");
      writer.println("            </div>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("</table>");
      writer.println("");
      writer.println("<table width=\"100%\" border=\"0\">");
      writer.println("    <tr>");
      writer.println("        <td colspan=\"3\" bgcolor=\"#FFFFCC\">");
      writer.println("            <strong>您预定的考试</strong>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=33%>");
      writer.println("            java");
      writer.println("        </td>");
      writer.println("        <td width=\"31%\">");
      writer.println("            Description");
      writer.println("        </td>");
      writer.println("        <td width=\"36%\">");
      writer.println("            <a href=\"startTest.html\">");
      writer.println("                开始考试");
      writer.println("            </a>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=33%>");
      writer.println("            java");
      writer.println("        </td>");
      writer.println("        <td width=\"31%\">");
      writer.println("            Description");
      writer.println("        </td>");
      writer.println("        <td width=\"36%\">");
      writer.println("            <a href=\"payment.html\">");
      writer.println("                预定考试");
      writer.println("            </a>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("    <tr>");
      writer.println("        <td width=33%>");
      writer.println("            java");
      writer.println("        </td>");
      writer.println("        <td width=\"31%\">");
      writer.println("            Description");
      writer.println("        </td>");
      writer.println("        <td width=\"36%\">");
      writer.println("            <a href=\"startTest.html\">");
      writer.println("                继续考试");
      writer.println("            </a>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("</table>");
      writer.println("");
      writer.println("<table width=\"100%\" border=\"0\">");
      writer.println("    <tr>");
      writer.println("        <td colspan=\"3\" valign=\"top\" bgcolor=\"#FFFFCC\">");
      writer.println("            <strong>您的考试记录</strong>");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("    <tr>");
      writer.println("        <td width=\"33%\">");
      writer.println("            getStartTime()");
      writer.println("        </td>");
      writer.println("        <td width=\"31%\">");
      writer.println("            <a href=\"testDetail.html\">JAVA</a>");
      writer.println("        </td>");
      writer.println("        <td width=\"36%\">");
      writer.println("            testResult().getValue());");
      writer.println("        </td>");
      writer.println("    </tr>");
      writer.println("");
      writer.println("</table>");

   }
}